name: 'cd publish'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - closed
permissions:
  pull-requests: write
  contents: 'read'
  id-token: 'write'

env:
  BUILD_VERSION: 2023.3

jobs:
  cd:
    name: 'cd-publish'
    runs-on: [self-hosted]

    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Python install'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 'build pkg'
      run: |
        cd hello-app
        pip install -r requirements.txt
        python -m build

    - name: 'build image'
      run: |
        docker build -t hello-app:$BUILD_VERSION -f ./hello-app/Dockerfile ./hello-app/
        # docker login && docker push

    - name: 'Create Draft Release'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: ${{ env.BUILD_VERSION }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hello-app/dist/yaw-${{ env.BUILD_VERSION }}.tar.gz
        asset_name: yaw.tar.gz
        asset_content_type: application/gzip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}

