name: 'do deploy'

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    name: 'do-deploy'
    runs-on: [self-hosted]

    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup terraform tools'
      uses: cds-snc/terraform-tools-setup@v1
      env:
        CONFTEST_VERSION: 0.30.0
        TERRAFORM_VERSION: 1.3.1
        TERRAGRUNT_VERSION: 0.38.12

    #- name: 'Configure aws credentials'
      #uses: aws-actions/configure-aws-credentials@v1
      #env:
        #AWS_REGION: 'us-west-1'
      #with:
        #aws-region: ${{ env.AWS_REGION }}
    #- name: 'Create Deployment'
      #run: |
        #cd infra/live/cloud/aws/yaw-eng-act/us-west-1/dev/yaw-svc
        #rm -rf ./.terragrunt-cache || true
        #rm -rf ./.terraform.lock.hcl || true
        #terragrunt apply --terragrunt-non-interactive --auto-approve
